apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t88uajxcm-go 
  janus-idp.io/tekton: t88uajxcm-go
  backstage.io/kubernetes-id: t88uajxcm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t88uajxcm-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  