apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t88uajxcm-go
  janus-idp.io/tekton: t88uajxcm-go
  backstage.io/kubernetes-id: t88uajxcm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t88uajxcm-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
